### PR TITLE
Add pythonpath

### PR DESCRIPTION
**Pull request by mattpauls**
Added default python path so Github's pytest can find our modules.

### CODE REVIEW

**Comment by mattpauls** [comment]
Hmm now it's failing because it can't find `rich`. Perhaps we need to install it using `pip` in the `python-test.yml` file.

**Comment by opensourcedev79** [comment]
Checkout #10. 

I forgot to add a step to install the package in the workflow. Instead of adding the dependencies in the workflow, we should install the package directly and make sure the dependencies come with it.

**Comment by mattpauls** [comment]
@opensourcedev79 Ah, okay, that makes more sense (although I am proud of myself for figuring it out, hacky as it was!). Still new to all this packaging stuff, I'll have to dig into that more.

**Comment by opensourcedev79** [comment]
Absolutely! This is great! 

When you get some time, try writing a unit test too 😉

**Comment by mattpauls** [comment]
Thanks man. Sounds good, will do!

**Pull request closed without merging**
